MAIN := tuo
SRCS := $(wildcard *.cpp)
OBJS := $(patsubst %.cpp,obj/%.o,$(SRCS))
INCS := $(wildcard *.h)

CPPFLAGS := -Wall -Werror -std=gnu++11 -Ofast -g -DNDEBUG -DNQUEST -DTUO_MODE_OPEN_THE_DECK2
LDFLAGS := -lboost_system -lboost_thread -lboost_filesystem -lboost_regex

all: $(MAIN)

obj/.stamp:
	mkdir -p obj
	touch obj/.stamp

obj/%.o: %.cpp $(INCS) obj/.stamp
	$(CXX) $(CPPFLAGS) -o $@ -c $<

$(MAIN): $(OBJS)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm -rf $(MAIN) obj/*.o
